server.port: 8082
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
#           enabled: true
           lowerCaseServiceId: true
      routes:
        - id: auth
          uri: lb://AUTH-SERVER/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: demoa
          uri: lb://DEMO-A/
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1

# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/