server:
  port: 7084
info:
  version: 1.0.1
  isGray: false
spring:
  application:
    name: demo-c
  cloud:
    nacos:
      discovery:
        metadata: {"version":@version@}
  kafka:
    bootstrap-servers: 10.33.80.101:9092
    consumer:
      group-id: demo-c
      auto-offset-reset: latest
      auto-commit-interval: 1000
      enable-auto-commit: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.80.101:3306/demo_c?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

fdfs:
  connect-timeout: 10000
  so-timeout: 3000
  tracker-list:
    - 10.33.80.144:22122

reliable:
  message:
    reliableMessageConsumer: true


topic:
  saveUser: SAVE_USER_1.0.0_DEMO-C

aaa: 23