logging:
  config: classpath:logback.xml
server:
  port: 8081

netty:
  server:
    ip: 127.0.0.1
    port: 9999
info:
  version: @version@
  isGray: true
spring:
  cloud:
    nacos:
      discovery:
        metadata: {"version":@version@}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.80.101:3306/demo_a?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456

  redis:
    host: 10.33.80.101
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    servlet:
      context-path:



reliable:
  message:
    reliableMessageProducer: true