server:
  port: 8081
info:
  version: 1.0.1
  isGray: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      version: ${info.version}
#      isGray: ${info.isGray}