server:
  port: 7080


info:
  version: 1.0.1
  isGray: false

spring:
  application:
    name: demo-b
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      version: ${info.version}
#      isGray: ${info.isGray}