server:
  port: 7081
info:
  version: 1.0.1
  isGray: false
spring:
  cloud:
    nacos:
      discovery:
        metadata: {"version":@version@}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_b?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

fdfs:
  connect-timeout: 10000
  so-timeout: 3000
  tracker-list:
    - 10.33.80.144:22122

reliable:
  message:
    reliableMessageConsumer: true
