server:
  port: 7080
info:
  version: 1.0.1
  isGray: false
spring:
  cloud:
    nacos:
      discovery:
        metadata: {"version":@version@}
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
fdfs:
  connect-timeout: 10000
  so-timeout: 3000
  tracker-list:
    - 10.33.80.144:22122